config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :flats

  resources :tenants

  get '/home', to: 'flats#home', as: 'home'
  post '/join', to: 'flats#join', as: 'join'
  post '/remove', to: 'flats#remove', as: 'remove'

  get '/find_tenant', to: 'tenants#find', as: 'find_tenant'





end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :street_address, presence: true
  validates :suburb, presence: true
  validates :post_code, presence: true
  validates :city, presence: true
  validates :country, presence: true
  validates :max_tenants_nums, presence: true
  validates :current_tenants_num, presence: true
  validates_numericality_of :current_tenants_num, :less_than_or_equal_to => :max_tenants_nums
  validates :lease_start_date, presence: true
  validates :length_of_lease, presence: true

  has_many :tenants
  has_many :users, through: :tenants
end

app/models/tenant.rb
class Tenant < ApplicationRecord
  validates :tenant_agreement_type, presence: true, inclusion: { in: %w(flatmate lease) }
  validates :head_tenant, inclusion: { in: [ true, false ] }

  belongs_to :flat
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tenants

  def country_name
    country = ISO3166::Country[nationality]
    country.translations[I18n.locale.to_s] || country.name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys:[:email, :password,:first_name, :last_name,:preferred_name,:nationality, :gender, :date_of_birth,:bio,:contact_number])
      devise_parameter_sanitizer.permit(:account_update, keys:[:email, :password, :current_password, :first_name, :last_name,:preferred_name,:nationality, :gender,:date_of_birth,:bio,:contact_number])
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new()
    @tenant = Tenant.new()
  end

  def show
    @flat = Flat.find(params[:id])
    @tenant = @flat.tenants
  end

  def create
   @flat = Flat.new(flat_params)
   @flat.save


   @tenant = Tenant.new
   @tenant.flat = @flat
   @flat.current_tenants_num += 1
   @tenant.user = current_user
   params[:other][:head_tenant] == 'true' ? @tenant.head_tenant = true : @tenant.head_tenant = false
   params[:other][:agreement_type] == 'Lease' ? @tenant.tenant_agreement_type = "lease" : @tenant.tenant_agreement_type = "flatmate"
   @tenant.save


   redirect_to home_path
  end

  def home
    @tenant = current_user.tenants.where(active_tenant: true)[0]
    if !@tenant.nil?
      @flat = @tenant.flat
      @active_tenants = @flat.tenants.where(active_tenant: true)
    end
  end

  def join
    flat = current_user.tenants.where(active_tenant: true)[0].flat
    new_tenant = User.find(params[:user][:id])
    tenant = Tenant.new
    tenant.user = new_tenant
    tenant.flat = flat
    tenant.tenant_agreement_type = 'lease' if params[:user][:agreement] == 'lease'
    tenant.tenant_agreement_type = 'flatmate' if params[:user][:agreement] == 'flatmate'
    tenant.head_tenant = false
    tenant.active_tenant = true
    if tenant.save
      flat.current_tenants_num += 1
      flat.save
    end
    redirect_to home_path
  end

  def remove
    tenant = Tenant.find(params[:tenant][:id])
    flat = tenant.flat
    tenant.active_tenant = false
    if tenant.save
      flat.current_tenants_num -= 1
      flat.save
    end
    redirect_to home_path
  end


  private

  def flat_params
    params.require(:flat).permit(:street_address, :suburb, :city, :post_code, :country, :max_tenants_nums, :lease_start_date, :length_of_lease)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
  def index

    @tenants = Tenant.all
  end

  def find
    sql_query = "email ILIKE :query OR last_name ILIKE :query OR first_name ILIKE :query"
    if params[:query].present?
      @users = User.where(sql_query, query: "%#{params[:query]}%")
    else
      @users = User.all
    end
  end

  def show
    @tenant = Tenant.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/flats/home.html.erb
<div class="container">
  <% if @tenant.nil? %>
  <div class="card">
    <div class="card-body">
      <h1>You currently are not sharing a flat.</h1>
      <%= link_to 'Create Your Own', new_flat_path %>
      <div>or<br> Request Your Head Tenant To Add You To Your Flat</div>
    </div>
  </div>


  <% else %>


  <div class="card text-center m-3">
    <div class="card-body">
      <h6>Welcome To</h6>
      <h1><%= @flat.street_address  %></h1>
      <p>Your flat currently has <%= @flat.current_tenants_num %> / <%= @flat.max_tenants_nums %> occupants</p>
      <%= link_to "Add A Flatmate", find_tenant_path %>
    </div>
  </div>
  <% end %>

  <% if !@active_tenants.nil? %>
    <div class='card m-3'>
      <h3>Your current flatmates are </h3>
      <div id="accordion">

      <% @active_tenants.each do |tenant| %>
        <% if tenant.user.id != current_user.id %>
          <% id = "collapse"+ tenant.id.to_s %>
          <% data = "#"+ id %>
          <% heading = "heading"+ tenant.id.to_s %>
          <div class="card">
            <div class="card-header" id="headingOne">
              <h5 class="mb-0">
                <button class="btn btn-link" data-toggle="collapse" data-target='<%= data %>' aria-expanded="true" aria-controls='<%= id  %>'>
                  <%= tenant.user.first_name + " " + tenant.user.last_name %>
                </button>
              </h5>
            </div>

            <div id='<%= id %>' class="collapse" aria-labelledby='<%= heading %>' data-parent="#accordion">
              <div class="card-body d-flex justify-content-between flex-column">
                <p><%= tenant.user.email  %></p>
                <p><%= tenant.user.date_of_birth %></p>
                <p><%= tenant.user.nationality  %></p>
                <p><%= tenant.user.bio.nil? ? "No Description" : tenant.user.bio  %>
                <%= link_to "View Profile", tenant_path(tenant), class: 'btn btn-primary'  %>
                <% if current_user.tenants.where(active_tenant: :true)[0].head_tenant == true %>
                  <%= link_to "Remove From Flat", remove_path(:tenant => {:id => tenant.id}), method: :post, class: 'btn btn-primary'  %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/flats/index.html.erb
<div class="container">

<ul class="list-group">
  <% @flats.each do |flat| %>
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <%= flat.flat_name.nil? ? flat.street_address : flat.flat_name  %>
    <span class="badge badge-primary badge-pill"><%= flat.current_tenants_num  %></span>
  </li>
  <% end %>
</ul>

</div>

app/views/flats/new.html.erb
<div class="container">
  <h2>Please Enter Your Flat Details</h2>

  <%= simple_form_for @flat do |f| %>
  <%= f.input :street_address %>
  <%= f.input :suburb %>
  <%= f.input :city %>
  <%= f.input :post_code %>
  <%= f.label :country  %>
  <%= f.country_select :country %>
  <%= f.input :max_tenants_nums %>
  <%= f.input :lease_start_date %>
  <%= f.input :length_of_lease %>

  <%= simple_fields_for :other do |o|  %>
    <%= o.input :head_tenant, as: :boolean, checked_value: true, unchecked_value: false %>
    <%= o.input :agreement_type, collection: ['Lease', 'Flatmate'], label: "What type of agreement are you on?"  %>
  <% end %>

  <%= f.button :submit %>
  <% end %>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsFlattyV2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>

  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Home", home_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Bills", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Support", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My Details", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>

      <% else %>
        <li class="nav-item">
          <%= link_to "How It Works", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About Us", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "FAQs", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/tenants/find.html.erb
<div class="container">

  <div class="search mb-3">
    <%= form_tag(find_tenant_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :query, params[:query], placeholder: "Search For Person By Name or Email", class: 'search-bar' %>
    <%= submit_tag "Search", class: 'btn btn-secondary ml-2 p-2 rounded-lg' %>
    <% end %>
  </div>



  <div id="accordion">
  <% @users.each do |user| %>
    <% id = "collapse"+ user.id.to_s %>
    <% data = "#"+ id %>
    <% heading = "heading"+ user.id.to_s %>
    <div class="card">
      <div class="card-header" id="headingOne">
        <h5 class="mb-0">
          <button class="btn btn-link" data-toggle="collapse" data-target="<%= data %>" aria-expanded="true" aria-controls="<%= id %>">
            <%= user.first_name + " " + user.last_name %>
          </button>
        </h5>
      </div>

      <div id="<%= id %>" class="collapse" aria-labelledby="<%= heading %>" data-parent="#accordion">
        <div class="card-body d-flex justify-content-between">
          <p><%= user.email  %></p>
          <p><%= user.date_of_birth %></p>
          <p><%= user.nationality  %></p>
          <p><%= user.bio.nil? ? "No Description" : user.bio  %>
          <span class="badge badge-primary badge-pill"><%= user.tenants.where(active_tenant: :true).length == 0 ? "Looking For A Flat" : "Sharing A Flat"  %></span>
        </div>
        <div class="card-footer">
          <p>Want to add Nipunee To Your Flat?</p>
          <%= link_to 'Add onto lease', join_path(:user => {:id => user.id, :agreement => 'lease' }), method: :post, class: "btn btn-primary" %>
          <%= link_to 'Add with flatmate agreement', join_path(:user => {:id => user.id, :agreement => 'flatmate' }) , method: :post, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
    <% end %>
    </div>


</div>

app/views/tenants/show.html.erb
<div class="container">
  <div class="card">
    <div class="card-body d-flex justify-content-between">
      <h1><%= @tenant.user.first_name + " " + @tenant.user.last_name %></h1>
      <% if current_user.tenant.head_tenant == true %>
        <%= link_to "Remove From Flat", '#', class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
   <div class="card">
    <div class="card-body">
      <h2>Personal Information</h2>
      <p><%= @tenant.user.date_of_birth %></p>
      <p><%= @tenant.user.nationality %></p>
      <p><%= @tenant.user.gender.titlecase %></p>
      <p><%= @tenant.user.bio.titlecase %></p>
    </div>
  </div>
     <div class="card">
    <div class="card-body">
      <h2>Contact Information</h2>
      <p><%= @tenant.user.contact_number %></p>
      <p><%= @tenant.user.email %></p>
    </div>
  </div>
</div>